### ISSUE TITLE
Stupid Permissions

### ISSUE THREAD

**Issue by TheEpicCooldeal** [LegendOfMCPE/EssentialsPE#103]
I'm not really into PHP Coding but I know some Java coding stuff and I KNOW that when you have a child permission to a permission it gives them access to that command and the child commands. 

That probably didn't make any sense.. Here's the thing:

```yaml
 essentials.clearinventory:
                default: op
                description: "Clear a player inventory"
                children:
                    essentials.clearinventory.other:
                        default: op
                        description: "Clear other's inventory"

essentials.fly:
                default: op
                description: "Fly in Survival or Adventure mode!"
                children:
                    essentials.fly.others:
                        default: op
                        description: "Make other players fly!"

essentials.god:
                default: op
                description: "Prevent a player to take any damage"
                children:
                    essentials.god.other:
                        default: op
                        description: "Prevent other players to take damage"
                    essentials.god.pvp:
                        default: op
                        description: "Let you attack other players while you're in god mode"

essentials.heal:
                default: op
                description: "Heal yourself or other players"
                children:
                    essentials.heal.other:
                        default: op
                        description: "Heal other players"

essentials.kit:
                default: true
                description: "Access to the /kit command"
                children:
                    essentials.kit.other:
                        default: op
                        description: "Give a kit to other players"

essentials.nick:
                default: op
                description: "Change your or others name"
                children:
                    essentials.nick.other:
                        default: op
                        description: "Change others name"
```

ALL OF THIS NEEDS TO BE CHANGED!! 
NO WONDER WHY MY DONATORS WHO HAD THE PERMISSION "essentials.nick" WERE ABLE TO CHANGE OTHER PEOPLE'S NICKS 
AND NO WONDER THAT PEOPLE WERE GETTING GOD MODE 
AND NO WONDER MY PLAYERS WHERE ABLE TO GIVE OTHER PLAYERS KITS 
AND NO WONDER MY DONATORS WHERE ABLE TO HEAL OTHER PLAYERS 
AND NO WONDER WHY PEOPLE WERE GETTING THE ABILITY TO FLY
