### ISSUE TITLE
Missing permissions error message getpos.other node

### ISSUE THREAD

**Issue by markkrueg** [LegendOfMCPE/EssentialsPE#214]
If I have permissions for a player set such that they have permission to getpos.use but not getpos.other, it works as intended, but when the player tries to getpos another player a blank line appears. 

I believe it is intended to have a red permissions error message?

Example permission tree for allowing getpos, but not for other:

```
Guest:
  isDefault: true
  inheritance: []
  permissions:
  - -essentials.kit
  - -essentials.kit.other
  - -pocketmine.command.me
  - essentials.getpos.use
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.command.list
  - pperms.command.ppinfo
  worlds: []
```
